_target_: src.models.age_module.AgeLitModule

optimizer:
  _target_: torch.optim.RAdam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.00001

net:
  _target_: src.models.components.efficient_net.EfficientNet
  name: 'efficientnet-b0'
  output_size: 1
